# Generated by Django 2.2.4 on 2019-08-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='code',
            old_name='program',
            new_name='body',
        ),
        migrations.AddField(
            model_name='code',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='created'),
            preserve_default=False,
        ),
    ]
