# Generated by Django 2.2.4 on 2019-08-19 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coder', '0002_auto_20190819_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coder_code', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
